### ISSUE TITLE
Setup structure graphique

### ISSUE THREAD

**Issue by lsagetlethias** [SocialGouv/archimail#16]
# Todo

- [ ] Reprendre la base graphique d'Archifiltre
- [ ] Définir (ou pas) un design system
- [ ] Mise en place des snapshot pour les tests de composant (si besoin)
- [ ] Idem pour Storybook
